info:
  scm-url: "http://120.79.93.249:8089/job/${spring.application.name}/"
  build-url: "https://github.com/shenxinli/spring-cloud-stage"
---
spring:
  rabbitmq:
    host: 120.79.93.249
    port: 5673
    username: shenxinli
    password: chinaway2014