EUREKA_SERVICE_URL: http://172.18.170.101:8761
security:
  user:
    name: "root"
    password: "123456"
info:
  scm-url: "https://github.com/shenxinli/spring-cloud-stage"
  build-url: "http://120.79.93.249:8089/job/${spring.application.name}/"
